spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MariaDBDialect
  cache:
    cache-names: SearchCache
    caffeine:
      spec: maximumSize=1000000, expireAfterWrite=600s
server:
  port: 5000
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          EnumType: TRACE
          descriptor:
            sql:
              BasicBinder: TRACE